# Generated by Django 4.2.1 on 2024-05-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_record_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='fisrt_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
    ]
